[environment]
cpu_count = 256
exec_env = "posix"
free_mem = 735.6
overcommit_policy = "always"
overcommit_limit = "50%"
nipype_version = "1.10.0"
templateflow_version = "24.2.2"
version = "25.0.0"

[execution]
bids_dir = "/nas/research/03-Neural_decoding/3-bids/raw_data"
bids_database_dir = "/nas/research/03-Neural_decoding/2-Bids_code/work/20250416-080613_62f9d40c-64e5-4f70-a370-d5d9eb9bc597/bids_db"
boilerplate_only = false
sloppy = false
debug = []
fmriprep_dir = "/nas/research/03-Neural_decoding/3-bids/derivatives/raw_roi_zscore"
fs_license_file = "/nas/research/03-Neural_decoding/license.txt"
fs_subjects_dir = "/nas/research/03-Neural_decoding/3-bids/derivatives/raw_roi_zscore/sourcedata/freesurfer"
layout = "BIDS Layout: ...eural_decoding/3-bids/raw_data | Subjects: 1 | Sessions: 40 | Runs: 12"
log_dir = "/nas/research/03-Neural_decoding/3-bids/derivatives/raw_roi_zscore/logs"
log_level = 25
low_mem = false
md_only_boilerplate = false
notrack = true
track_carbon = false
country_code = "CAN"
output_dir = "/nas/research/03-Neural_decoding/3-bids/derivatives/raw_roi_zscore"
me_output_echos = false
aggr_ses_reports = 4
output_layout = "bids"
output_spaces = "MNI152NLin2009cAsym:res-native"
reports_only = false
run_uuid = "20250416-080613_62f9d40c-64e5-4f70-a370-d5d9eb9bc597"
participant_label = [ "01",]
templateflow_home = "/root/.cache/templateflow"
work_dir = "/nas/research/03-Neural_decoding/2-Bids_code/work"
write_graph = false

[workflow]
anat_only = false
bold2anat_dof = 6
bold2anat_init = "auto"
cifti_output = false
fmap_bspline = false
force_syn = false
hires = true
fs_no_resume = false
ignore = []
force = []
level = "full"
longitudinal = false
run_msmsulc = true
medial_surface_nan = false
project_goodvoxels = false
regressors_all_comps = false
regressors_dvars_th = 1.5
regressors_fd_th = 0.5
run_reconall = true
skull_strip_fixed_seed = false
skull_strip_template = "OASIS30ANTs"
skull_strip_t1w = "force"
slice_time_ref = 0.5
use_syn_sdc = false
me_t2s_fit_method = "curvefit"

[nipype]
crashfile_format = "txt"
get_linked_libs = false
nprocs = 256
omp_nthreads = 8
plugin = "MultiProc"
remove_unnecessary_outputs = true
resource_monitor = false
stop_on_first_crash = false

[seeds]
master = 21177
ants = 56346
numpy = 39423

[execution.derivatives]

[execution.dataset_links]
raw = "/nas/research/03-Neural_decoding/3-bids/raw_data"
templateflow = "/root/.cache/templateflow"

[nipype.plugin_args]
maxtasksperchild = 1
raise_insufficient = false
